/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.ide;

import poli.compiladores.rec.ide.AbstractRectrineIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RectrineIdeModule extends AbstractRectrineIdeModule {
}
