/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import poli.compiladores.rec.RectrineRuntimeModule;
import poli.compiladores.rec.RectrineStandaloneSetup;
import poli.compiladores.rec.ide.RectrineIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RectrineIdeSetup extends RectrineStandaloneSetup {
  @Override
  public Injector createInjector() {
    RectrineRuntimeModule _rectrineRuntimeModule = new RectrineRuntimeModule();
    RectrineIdeModule _rectrineIdeModule = new RectrineIdeModule();
    return Guice.createInjector(Modules2.mixin(_rectrineRuntimeModule, _rectrineIdeModule));
  }
}
