/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.rectrine.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import poli.compiladores.rec.rectrine.Entidade;
import poli.compiladores.rec.rectrine.Ligacao;
import poli.compiladores.rec.rectrine.RectrinePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ligacao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link poli.compiladores.rec.rectrine.impl.LigacaoImpl#getEnt1 <em>Ent1</em>}</li>
 *   <li>{@link poli.compiladores.rec.rectrine.impl.LigacaoImpl#getMul1 <em>Mul1</em>}</li>
 *   <li>{@link poli.compiladores.rec.rectrine.impl.LigacaoImpl#getMul2 <em>Mul2</em>}</li>
 *   <li>{@link poli.compiladores.rec.rectrine.impl.LigacaoImpl#getEnt2 <em>Ent2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LigacaoImpl extends MinimalEObjectImpl.Container implements Ligacao
{
  /**
   * The cached value of the '{@link #getEnt1() <em>Ent1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnt1()
   * @generated
   * @ordered
   */
  protected Entidade ent1;

  /**
   * The default value of the '{@link #getMul1() <em>Mul1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMul1()
   * @generated
   * @ordered
   */
  protected static final String MUL1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMul1() <em>Mul1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMul1()
   * @generated
   * @ordered
   */
  protected String mul1 = MUL1_EDEFAULT;

  /**
   * The default value of the '{@link #getMul2() <em>Mul2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMul2()
   * @generated
   * @ordered
   */
  protected static final String MUL2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMul2() <em>Mul2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMul2()
   * @generated
   * @ordered
   */
  protected String mul2 = MUL2_EDEFAULT;

  /**
   * The cached value of the '{@link #getEnt2() <em>Ent2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnt2()
   * @generated
   * @ordered
   */
  protected Entidade ent2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LigacaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RectrinePackage.Literals.LIGACAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidade getEnt1()
  {
    if (ent1 != null && ent1.eIsProxy())
    {
      InternalEObject oldEnt1 = (InternalEObject)ent1;
      ent1 = (Entidade)eResolveProxy(oldEnt1);
      if (ent1 != oldEnt1)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RectrinePackage.LIGACAO__ENT1, oldEnt1, ent1));
      }
    }
    return ent1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidade basicGetEnt1()
  {
    return ent1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnt1(Entidade newEnt1)
  {
    Entidade oldEnt1 = ent1;
    ent1 = newEnt1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RectrinePackage.LIGACAO__ENT1, oldEnt1, ent1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMul1()
  {
    return mul1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMul1(String newMul1)
  {
    String oldMul1 = mul1;
    mul1 = newMul1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RectrinePackage.LIGACAO__MUL1, oldMul1, mul1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMul2()
  {
    return mul2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMul2(String newMul2)
  {
    String oldMul2 = mul2;
    mul2 = newMul2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RectrinePackage.LIGACAO__MUL2, oldMul2, mul2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidade getEnt2()
  {
    if (ent2 != null && ent2.eIsProxy())
    {
      InternalEObject oldEnt2 = (InternalEObject)ent2;
      ent2 = (Entidade)eResolveProxy(oldEnt2);
      if (ent2 != oldEnt2)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RectrinePackage.LIGACAO__ENT2, oldEnt2, ent2));
      }
    }
    return ent2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entidade basicGetEnt2()
  {
    return ent2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnt2(Entidade newEnt2)
  {
    Entidade oldEnt2 = ent2;
    ent2 = newEnt2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RectrinePackage.LIGACAO__ENT2, oldEnt2, ent2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RectrinePackage.LIGACAO__ENT1:
        if (resolve) return getEnt1();
        return basicGetEnt1();
      case RectrinePackage.LIGACAO__MUL1:
        return getMul1();
      case RectrinePackage.LIGACAO__MUL2:
        return getMul2();
      case RectrinePackage.LIGACAO__ENT2:
        if (resolve) return getEnt2();
        return basicGetEnt2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RectrinePackage.LIGACAO__ENT1:
        setEnt1((Entidade)newValue);
        return;
      case RectrinePackage.LIGACAO__MUL1:
        setMul1((String)newValue);
        return;
      case RectrinePackage.LIGACAO__MUL2:
        setMul2((String)newValue);
        return;
      case RectrinePackage.LIGACAO__ENT2:
        setEnt2((Entidade)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RectrinePackage.LIGACAO__ENT1:
        setEnt1((Entidade)null);
        return;
      case RectrinePackage.LIGACAO__MUL1:
        setMul1(MUL1_EDEFAULT);
        return;
      case RectrinePackage.LIGACAO__MUL2:
        setMul2(MUL2_EDEFAULT);
        return;
      case RectrinePackage.LIGACAO__ENT2:
        setEnt2((Entidade)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RectrinePackage.LIGACAO__ENT1:
        return ent1 != null;
      case RectrinePackage.LIGACAO__MUL1:
        return MUL1_EDEFAULT == null ? mul1 != null : !MUL1_EDEFAULT.equals(mul1);
      case RectrinePackage.LIGACAO__MUL2:
        return MUL2_EDEFAULT == null ? mul2 != null : !MUL2_EDEFAULT.equals(mul2);
      case RectrinePackage.LIGACAO__ENT2:
        return ent2 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (mul1: ");
    result.append(mul1);
    result.append(", mul2: ");
    result.append(mul2);
    result.append(')');
    return result.toString();
  }

} //LigacaoImpl
