/*
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RectrineRuntimeModule extends AbstractRectrineRuntimeModule {
}
