/*
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import poli.compiladores.rec.ui.internal.RecActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RectrineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RecActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RecActivator.getInstance().getInjector(RecActivator.POLI_COMPILADORES_REC_RECTRINE);
	}
	
}
