/**
 * generated by Xtext 2.12.0
 */
package poli.computadores.rectrine;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Campo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link poli.computadores.rectrine.Campo#getName <em>Name</em>}</li>
 *   <li>{@link poli.computadores.rectrine.Campo#getTipo <em>Tipo</em>}</li>
 *   <li>{@link poli.computadores.rectrine.Campo#getRel <em>Rel</em>}</li>
 * </ul>
 *
 * @see poli.computadores.rectrine.RectrinePackage#getCampo()
 * @model
 * @generated
 */
public interface Campo extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see poli.computadores.rectrine.RectrinePackage#getCampo_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link poli.computadores.rectrine.Campo#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see poli.computadores.rectrine.RectrinePackage#getCampo_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link poli.computadores.rectrine.Campo#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

  /**
   * Returns the value of the '<em><b>Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rel</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel</em>' containment reference.
   * @see #setRel(Ligacao)
   * @see poli.computadores.rectrine.RectrinePackage#getCampo_Rel()
   * @model containment="true"
   * @generated
   */
  Ligacao getRel();

  /**
   * Sets the value of the '{@link poli.computadores.rectrine.Campo#getRel <em>Rel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel</em>' containment reference.
   * @see #getRel()
   * @generated
   */
  void setRel(Ligacao value);

} // Campo
