/*
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class RectrineWebModule extends AbstractRectrineWebModule {
}
