/**
 * generated by Xtext 2.12.0
 */
package poli.computadores.validation;

import poli.computadores.validation.AbstractRectrineValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RectrineValidator extends AbstractRectrineValidator {
}
