/*
 * generated by Xtext 2.12.0
 */
package poli.computadores.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import poli.computadores.parser.antlr.internal.InternalRectrineParser;
import poli.computadores.services.RectrineGrammarAccess;

public class RectrineParser extends AbstractAntlrParser {

	@Inject
	private RectrineGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRectrineParser createParser(XtextTokenStream stream) {
		return new InternalRectrineParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public RectrineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RectrineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
