/*
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRectrineValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(poli.compiladores.rec.rectrine.RectrinePackage.eINSTANCE);
		return result;
	}
	
}
