/*
 * generated by Xtext 2.12.0
 */
package poli.computadores.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RectrineWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRectrineWebModule extends DefaultWebModule {

}
