/**
 * generated by Xtext 2.12.0
 */
package poli.computadores.ui.contentassist;

import poli.computadores.ui.contentassist.AbstractRectrineProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RectrineProposalProvider extends AbstractRectrineProposalProvider {
}
