/**
 * generated by Xtext 2.12.0
 */
package poli.computadores.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import poli.computadores.RectrineRuntimeModule;
import poli.computadores.RectrineStandaloneSetup;
import poli.computadores.ide.RectrineIdeModule;
import poli.computadores.web.RectrineWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class RectrineWebSetup extends RectrineStandaloneSetup {
  @Override
  public Injector createInjector() {
    RectrineRuntimeModule _rectrineRuntimeModule = new RectrineRuntimeModule();
    RectrineIdeModule _rectrineIdeModule = new RectrineIdeModule();
    RectrineWebModule _rectrineWebModule = new RectrineWebModule();
    return Guice.createInjector(Modules2.mixin(_rectrineRuntimeModule, _rectrineIdeModule, _rectrineWebModule));
  }
}
