/**
 * generated by Xtext 2.12.0
 */
package poli.computadores.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import poli.computadores.ui.AbstractRectrineUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RectrineUiModule extends AbstractRectrineUiModule {
  public RectrineUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
