/*
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRectrineScopeProvider extends DelegatingScopeProvider {
}
