/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.web;

import poli.compiladores.rec.web.AbstractRectrineWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class RectrineWebModule extends AbstractRectrineWebModule {
}
