/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec;

import poli.compiladores.rec.RectrineStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RectrineStandaloneSetup extends RectrineStandaloneSetupGenerated {
  public static void doSetup() {
    new RectrineStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
