/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec;

import poli.compiladores.rec.AbstractRectrineRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RectrineRuntimeModule extends AbstractRectrineRuntimeModule {
}
