/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.rectrine;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entidade</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link poli.compiladores.rec.rectrine.Entidade#getName <em>Name</em>}</li>
 *   <li>{@link poli.compiladores.rec.rectrine.Entidade#getCampos <em>Campos</em>}</li>
 * </ul>
 *
 * @see poli.compiladores.rec.rectrine.RectrinePackage#getEntidade()
 * @model
 * @generated
 */
public interface Entidade extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see poli.compiladores.rec.rectrine.RectrinePackage#getEntidade_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link poli.compiladores.rec.rectrine.Entidade#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Campos</b></em>' containment reference list.
   * The list contents are of type {@link poli.compiladores.rec.rectrine.Campo}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Campos</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Campos</em>' containment reference list.
   * @see poli.compiladores.rec.rectrine.RectrinePackage#getEntidade_Campos()
   * @model containment="true"
   * @generated
   */
  EList<Campo> getCampos();

} // Entidade
