/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.rectrine;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ligacao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link poli.compiladores.rec.rectrine.Ligacao#getEnt1 <em>Ent1</em>}</li>
 *   <li>{@link poli.compiladores.rec.rectrine.Ligacao#getMul1 <em>Mul1</em>}</li>
 *   <li>{@link poli.compiladores.rec.rectrine.Ligacao#getMul2 <em>Mul2</em>}</li>
 *   <li>{@link poli.compiladores.rec.rectrine.Ligacao#getEnt2 <em>Ent2</em>}</li>
 * </ul>
 *
 * @see poli.compiladores.rec.rectrine.RectrinePackage#getLigacao()
 * @model
 * @generated
 */
public interface Ligacao extends EObject
{
  /**
   * Returns the value of the '<em><b>Ent1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ent1</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ent1</em>' reference.
   * @see #setEnt1(Entidade)
   * @see poli.compiladores.rec.rectrine.RectrinePackage#getLigacao_Ent1()
   * @model
   * @generated
   */
  Entidade getEnt1();

  /**
   * Sets the value of the '{@link poli.compiladores.rec.rectrine.Ligacao#getEnt1 <em>Ent1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ent1</em>' reference.
   * @see #getEnt1()
   * @generated
   */
  void setEnt1(Entidade value);

  /**
   * Returns the value of the '<em><b>Mul1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mul1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mul1</em>' attribute.
   * @see #setMul1(String)
   * @see poli.compiladores.rec.rectrine.RectrinePackage#getLigacao_Mul1()
   * @model
   * @generated
   */
  String getMul1();

  /**
   * Sets the value of the '{@link poli.compiladores.rec.rectrine.Ligacao#getMul1 <em>Mul1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mul1</em>' attribute.
   * @see #getMul1()
   * @generated
   */
  void setMul1(String value);

  /**
   * Returns the value of the '<em><b>Mul2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mul2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mul2</em>' attribute.
   * @see #setMul2(String)
   * @see poli.compiladores.rec.rectrine.RectrinePackage#getLigacao_Mul2()
   * @model
   * @generated
   */
  String getMul2();

  /**
   * Sets the value of the '{@link poli.compiladores.rec.rectrine.Ligacao#getMul2 <em>Mul2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mul2</em>' attribute.
   * @see #getMul2()
   * @generated
   */
  void setMul2(String value);

  /**
   * Returns the value of the '<em><b>Ent2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ent2</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ent2</em>' reference.
   * @see #setEnt2(Entidade)
   * @see poli.compiladores.rec.rectrine.RectrinePackage#getLigacao_Ent2()
   * @model
   * @generated
   */
  Entidade getEnt2();

  /**
   * Sets the value of the '{@link poli.compiladores.rec.rectrine.Ligacao#getEnt2 <em>Ent2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ent2</em>' reference.
   * @see #getEnt2()
   * @generated
   */
  void setEnt2(Entidade value);

} // Ligacao
