/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.rectrine;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link poli.compiladores.rec.rectrine.Program#getEntidades <em>Entidades</em>}</li>
 * </ul>
 *
 * @see poli.compiladores.rec.rectrine.RectrinePackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Entidades</b></em>' containment reference list.
   * The list contents are of type {@link poli.compiladores.rec.rectrine.Entidade}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entidades</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entidades</em>' containment reference list.
   * @see poli.compiladores.rec.rectrine.RectrinePackage#getProgram_Entidades()
   * @model containment="true"
   * @generated
   */
  EList<Entidade> getEntidades();

} // Program
