/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.rectrine;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see poli.compiladores.rec.rectrine.RectrinePackage
 * @generated
 */
public interface RectrineFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RectrineFactory eINSTANCE = poli.compiladores.rec.rectrine.impl.RectrineFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Entidade</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entidade</em>'.
   * @generated
   */
  Entidade createEntidade();

  /**
   * Returns a new object of class '<em>Campo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Campo</em>'.
   * @generated
   */
  Campo createCampo();

  /**
   * Returns a new object of class '<em>Ligacao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ligacao</em>'.
   * @generated
   */
  Ligacao createLigacao();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RectrinePackage getRectrinePackage();

} //RectrineFactory
