/**
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.rectrine;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see poli.compiladores.rec.rectrine.RectrineFactory
 * @model kind="package"
 * @generated
 */
public interface RectrinePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rectrine";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.compiladores.poli/rec/Rectrine";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rectrine";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RectrinePackage eINSTANCE = poli.compiladores.rec.rectrine.impl.RectrinePackageImpl.init();

  /**
   * The meta object id for the '{@link poli.compiladores.rec.rectrine.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poli.compiladores.rec.rectrine.impl.ProgramImpl
   * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Entidades</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__ENTIDADES = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link poli.compiladores.rec.rectrine.impl.EntidadeImpl <em>Entidade</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poli.compiladores.rec.rectrine.impl.EntidadeImpl
   * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getEntidade()
   * @generated
   */
  int ENTIDADE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE__NAME = 0;

  /**
   * The feature id for the '<em><b>Campos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE__CAMPOS = 1;

  /**
   * The number of structural features of the '<em>Entidade</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDADE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link poli.compiladores.rec.rectrine.impl.CampoImpl <em>Campo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poli.compiladores.rec.rectrine.impl.CampoImpl
   * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getCampo()
   * @generated
   */
  int CAMPO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO__TIPO = 1;

  /**
   * The feature id for the '<em><b>Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO__REL = 2;

  /**
   * The number of structural features of the '<em>Campo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMPO_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link poli.compiladores.rec.rectrine.impl.LigacaoImpl <em>Ligacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poli.compiladores.rec.rectrine.impl.LigacaoImpl
   * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getLigacao()
   * @generated
   */
  int LIGACAO = 3;

  /**
   * The feature id for the '<em><b>Ent1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGACAO__ENT1 = 0;

  /**
   * The feature id for the '<em><b>Mul1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGACAO__MUL1 = 1;

  /**
   * The feature id for the '<em><b>Mul2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGACAO__MUL2 = 2;

  /**
   * The feature id for the '<em><b>Ent2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGACAO__ENT2 = 3;

  /**
   * The number of structural features of the '<em>Ligacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGACAO_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link poli.compiladores.rec.rectrine.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see poli.compiladores.rec.rectrine.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link poli.compiladores.rec.rectrine.Program#getEntidades <em>Entidades</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entidades</em>'.
   * @see poli.compiladores.rec.rectrine.Program#getEntidades()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Entidades();

  /**
   * Returns the meta object for class '{@link poli.compiladores.rec.rectrine.Entidade <em>Entidade</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidade</em>'.
   * @see poli.compiladores.rec.rectrine.Entidade
   * @generated
   */
  EClass getEntidade();

  /**
   * Returns the meta object for the attribute '{@link poli.compiladores.rec.rectrine.Entidade#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poli.compiladores.rec.rectrine.Entidade#getName()
   * @see #getEntidade()
   * @generated
   */
  EAttribute getEntidade_Name();

  /**
   * Returns the meta object for the containment reference list '{@link poli.compiladores.rec.rectrine.Entidade#getCampos <em>Campos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Campos</em>'.
   * @see poli.compiladores.rec.rectrine.Entidade#getCampos()
   * @see #getEntidade()
   * @generated
   */
  EReference getEntidade_Campos();

  /**
   * Returns the meta object for class '{@link poli.compiladores.rec.rectrine.Campo <em>Campo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Campo</em>'.
   * @see poli.compiladores.rec.rectrine.Campo
   * @generated
   */
  EClass getCampo();

  /**
   * Returns the meta object for the attribute '{@link poli.compiladores.rec.rectrine.Campo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poli.compiladores.rec.rectrine.Campo#getName()
   * @see #getCampo()
   * @generated
   */
  EAttribute getCampo_Name();

  /**
   * Returns the meta object for the attribute '{@link poli.compiladores.rec.rectrine.Campo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see poli.compiladores.rec.rectrine.Campo#getTipo()
   * @see #getCampo()
   * @generated
   */
  EAttribute getCampo_Tipo();

  /**
   * Returns the meta object for the containment reference '{@link poli.compiladores.rec.rectrine.Campo#getRel <em>Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rel</em>'.
   * @see poli.compiladores.rec.rectrine.Campo#getRel()
   * @see #getCampo()
   * @generated
   */
  EReference getCampo_Rel();

  /**
   * Returns the meta object for class '{@link poli.compiladores.rec.rectrine.Ligacao <em>Ligacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligacao</em>'.
   * @see poli.compiladores.rec.rectrine.Ligacao
   * @generated
   */
  EClass getLigacao();

  /**
   * Returns the meta object for the reference '{@link poli.compiladores.rec.rectrine.Ligacao#getEnt1 <em>Ent1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ent1</em>'.
   * @see poli.compiladores.rec.rectrine.Ligacao#getEnt1()
   * @see #getLigacao()
   * @generated
   */
  EReference getLigacao_Ent1();

  /**
   * Returns the meta object for the attribute '{@link poli.compiladores.rec.rectrine.Ligacao#getMul1 <em>Mul1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mul1</em>'.
   * @see poli.compiladores.rec.rectrine.Ligacao#getMul1()
   * @see #getLigacao()
   * @generated
   */
  EAttribute getLigacao_Mul1();

  /**
   * Returns the meta object for the attribute '{@link poli.compiladores.rec.rectrine.Ligacao#getMul2 <em>Mul2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mul2</em>'.
   * @see poli.compiladores.rec.rectrine.Ligacao#getMul2()
   * @see #getLigacao()
   * @generated
   */
  EAttribute getLigacao_Mul2();

  /**
   * Returns the meta object for the reference '{@link poli.compiladores.rec.rectrine.Ligacao#getEnt2 <em>Ent2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ent2</em>'.
   * @see poli.compiladores.rec.rectrine.Ligacao#getEnt2()
   * @see #getLigacao()
   * @generated
   */
  EReference getLigacao_Ent2();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RectrineFactory getRectrineFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link poli.compiladores.rec.rectrine.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poli.compiladores.rec.rectrine.impl.ProgramImpl
     * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Entidades</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__ENTIDADES = eINSTANCE.getProgram_Entidades();

    /**
     * The meta object literal for the '{@link poli.compiladores.rec.rectrine.impl.EntidadeImpl <em>Entidade</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poli.compiladores.rec.rectrine.impl.EntidadeImpl
     * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getEntidade()
     * @generated
     */
    EClass ENTIDADE = eINSTANCE.getEntidade();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTIDADE__NAME = eINSTANCE.getEntidade_Name();

    /**
     * The meta object literal for the '<em><b>Campos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTIDADE__CAMPOS = eINSTANCE.getEntidade_Campos();

    /**
     * The meta object literal for the '{@link poli.compiladores.rec.rectrine.impl.CampoImpl <em>Campo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poli.compiladores.rec.rectrine.impl.CampoImpl
     * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getCampo()
     * @generated
     */
    EClass CAMPO = eINSTANCE.getCampo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMPO__NAME = eINSTANCE.getCampo_Name();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMPO__TIPO = eINSTANCE.getCampo_Tipo();

    /**
     * The meta object literal for the '<em><b>Rel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMPO__REL = eINSTANCE.getCampo_Rel();

    /**
     * The meta object literal for the '{@link poli.compiladores.rec.rectrine.impl.LigacaoImpl <em>Ligacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poli.compiladores.rec.rectrine.impl.LigacaoImpl
     * @see poli.compiladores.rec.rectrine.impl.RectrinePackageImpl#getLigacao()
     * @generated
     */
    EClass LIGACAO = eINSTANCE.getLigacao();

    /**
     * The meta object literal for the '<em><b>Ent1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGACAO__ENT1 = eINSTANCE.getLigacao_Ent1();

    /**
     * The meta object literal for the '<em><b>Mul1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGACAO__MUL1 = eINSTANCE.getLigacao_Mul1();

    /**
     * The meta object literal for the '<em><b>Mul2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGACAO__MUL2 = eINSTANCE.getLigacao_Mul2();

    /**
     * The meta object literal for the '<em><b>Ent2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIGACAO__ENT2 = eINSTANCE.getLigacao_Ent2();

  }

} //RectrinePackage
