/*
 * generated by Xtext 2.12.0
 */
package poli.computadores.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import poli.compiladores.rectrine.ui.internal.RectrineActivator;

public class RectrineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RectrineActivator.getInstance().getInjector("poli.computadores.Rectrine");
	}

}
