/*
 * generated by Xtext 2.12.0
 */
package poli.compiladores.rec.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import poli.compiladores.rec.ui.internal.RecActivator;

public class RectrineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RecActivator.getInstance().getInjector("poli.compiladores.rec.Rectrine");
	}

}
