/*
 * generated by Xtext 2.12.0
 */
package poli.computadores


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RectrineStandaloneSetup extends RectrineStandaloneSetupGenerated {

	def static void doSetup() {
		new RectrineStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
